# Generated by Django 3.2.7 on 2021-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_link',
            field=models.CharField(default='https://www.pablopicasso.org/images/paintings/self-portrait.jpg', max_length=300),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(default='self-portrait', max_length=50),
        ),
    ]
