# Generated by Django 3.2.7 on 2021-09-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210908_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
