# Generated by Django 3.2.7 on 2021-09-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210908_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
