# Generated by Django 3.2.7 on 2021-09-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='character',
            new_name='post',
        ),
    ]
