# Generated by Django 3.2.7 on 2021-09-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
